name: Check Source Code

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-slim

    env:
      BIN_PATH: "${{ github.workspace }}/tools/bin"
      CHECKSUM_GDSCRIPT_FORMATTER: "77a5a0f3f3317b00ae2817c5f6c7461b8f597faec19e04fdc308191d43f5f2a8"
      GDSCRIPT_FORMATTER_VERSION: "0.18.2"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache GDScript Formatter
        id: cache-gdscript-formatter
        uses: actions/cache@v4
        with:
          path: ${{ env.BIN_PATH }}
          key: gdscript-formatter-${{ env.GDSCRIPT_FORMATTER_VERSION }}

      - name: Install GDScript Formatter
        if: steps.cache-gdscript-formatter.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{ env.BIN_PATH }}

          curl -L "https://github.com/GDQuest/GDScript-formatter/releases/download/${{ env.GDSCRIPT_FORMATTER_VERSION }}/gdscript-formatter-${{ env.GDSCRIPT_FORMATTER_VERSION }}-linux-x86_64.zip" -o gdscript-formatter.zip
          echo "${{ env.CHECKSUM_GDSCRIPT_FORMATTER }}  gdscript-formatter.zip" | sha256sum --check

          unzip -q gdscript-formatter.zip -d ${{ env.BIN_PATH }}
          rm gdscript-formatter.zip
          
          mv ${{ env.BIN_PATH }}/gdscript-formatter-${{ env.GDSCRIPT_FORMATTER_VERSION }}-linux-x86_64 ${{ env.BIN_PATH }}/gdscript-formatter
          chmod +x ${{ env.BIN_PATH }}/gdscript-formatter
          
          ${{ env.BIN_PATH }}/gdscript-formatter --version

      - name: Add Bin Path to PATH
        run: echo "${{ env.BIN_PATH }}" >> $GITHUB_PATH

      - name: Check GDScript Files
        run: |
          # gdscript-formatter does _not_ tell us what is wrong with the file's
          # format or _even what the failed file's name is_. ;-;
          #
          # Oh, and it does not support glob patterns.
          #
          # So, manual looping and file name printing~!
          find . -name "*.gd" -not -path "./addons/*" | while read -r file; do
            echo "Checking: $file"

            if ! gdscript-formatter --check "$file"; then
              echo "::error file=$file::Formatting failed on this file."
              exit 1
            fi
          done

      - name: Lint GDScript Files
        run: |
          find . -name "*.gd" -not -path "./addons/*" | while read -r file; do
            echo "Linting: $file"

            if ! gdscript-formatter lint --pretty "$file"; then
              echo "::error file=$file::Linting failed on this file."
              exit 1
            fi
          done
