# FORKED: https://github.com/abarichello/godot-ci/blob/9760acc92f68deb947b5b9dd62cc6aaad7dbc3ed/.github/workflows/godot-ci.yml

name: Release Artifacts

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  ANDROID_SDK_BUILD_TOOLS_VERSION: "35.0.1"
  ANDROID_SDK_COMMAND_LINE_TOOLS_VERSION: "14742923"
  ANDROID_SDK_CMAKE_VERSION: "3.10.2.4988404"
  ANDROID_SDK_NDK_VERSION: "28.1.13356709"
  ANDROID_SDK_PLATFORMS_VERSION: "android-35"
  BIN_ANDROID_SDK_PATH: "${{ github.workspace }}/tools/android_sdk"
  BIN_ANDROID_SDK_CMDLINE_TOOLS_PATH: "${{ github.workspace }}/tools/android_sdk/cmdline-tools/14742923"
  BIN_GODOT_PATH: "${{ github.workspace }}/tools/godot"
  BIN_JDK_PATH: "${{ github.workspace }}/tools/jdk"
  CHECKSUM_ANDROID_SDK_COMMAND_LINE_TOOLS: "04453066b540409d975c676d781da1477479dde3761310f1a7eb92a1dfb15af7"
  CHECKSUM_GODOT: "02ec53d1cc7dbb9cc6355393c61b9ab43d1244751a124f10248a4802830788cd"
  CHECKSUM_GODOT_TEMPLATES: "1998af37f1387684e2c211cdb483daf492fc64dc6b12096bddcdca25b6910c86"
  CHECKSUM_JDK: "0c94cbb54325c40dcf026143eb621562017db5525727f2d9131a11250f72c450"
  JDK_VERSION_ARCHIVE: "17.0.18_8"
  JDK_VERSION_TAG: "jdk-17.0.18+8"
  EXPORT_NAME: "spotnik"
  GODOT_VERSION: "4.5.1"
  PROJECT_PATH: "."

jobs:
  check:
    uses: ./.github/workflows/check-source-code.yaml

  install-godot:
    needs: check
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Repository Actions
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/actions/download-verify-extract-cache-archive

      - name: Install Godot
        id: godot-cache
        uses: ./.github/actions/download-verify-extract-cache-archive
        with:
          url: "https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip"
          checksum: ${{ env.CHECKSUM_GODOT }}
          archive-type: zip
          extract-path: ${{ env.BIN_GODOT_PATH }}
          cache-key-prefix: godot-${{ env.GODOT_VERSION }}

      - name: Rename Godot Binary
        if: steps.godot-cache.outputs.cache-hit != 'true'
        run: |
          mv ${{ env.BIN_GODOT_PATH }}/Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64 ${{ env.BIN_GODOT_PATH }}/godot

      - name: Setup File Permissions
        if: steps.godot-cache.outputs.cache-hit != 'true'
        run: |
          chmod +x ${{ env.BIN_GODOT_PATH }}/godot

  install-godot-templates:
    needs: check
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Repository Actions
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/actions/download-verify-extract-cache-archive

      - name: Configure Godot Templates Environment
        run: |
          echo "ASSETS_GODOT_TEMPLATES_PATH=${HOME}/.local/share/godot/export_templates" >> $GITHUB_ENV

      - name: Install Godot Templates
        id: godot-templates-cache
        uses: ./.github/actions/download-verify-extract-cache-archive
        with:
          url: "https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz"
          checksum: ${{ env.CHECKSUM_GODOT_TEMPLATES }}
          archive-type: zip
          extract-path: ${{ env.ASSETS_GODOT_TEMPLATES_PATH }}
          cache-key-prefix: godot-${{ env.GODOT_VERSION }}-templates

      - name: Rename Godot Templates Directory
        if: steps.godot-templates-cache.outputs.cache-hit != 'true'
        run: |
          mv ${{ env.ASSETS_GODOT_TEMPLATES_PATH }}/templates ${{ env.ASSETS_GODOT_TEMPLATES_PATH }}/${{ env.GODOT_VERSION }}.stable

  install-jdk:
    needs: check
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Repository Actions
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/actions/download-verify-extract-cache-archive

      - name: Install Adoptium Temurin JDK
        id: jdk-cache
        uses: ./.github/actions/download-verify-extract-cache-archive
        with:
          url: "https://github.com/adoptium/temurin17-binaries/releases/download/${{ env.JDK_VERSION_TAG }}/OpenJDK17U-jdk_x64_linux_hotspot_${{ env.JDK_VERSION_ARCHIVE }}.tar.gz"
          checksum: ${{ env.CHECKSUM_JDK }}
          archive-type: tar.gz
          extract-path: ${{ env.BIN_JDK_PATH }}
          cache-key-prefix: adoptium-temurin-${{ env.JDK_VERSION_TAG }}

      - name: Rename Adoptium Temurin JDK Directory
        if: steps.jdk-cache.outputs.cache-hit != 'true'
        run: |
          mv ${{ env.BIN_JDK_PATH }}/${{ env.JDK_VERSION_TAG }}/* ${{ env.BIN_JDK_PATH }}

  install-android-sdk:
    needs: [check, install-jdk]
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Repository Actions
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions/download-verify-extract-cache-archive
            .github/actions/restore-cached-archive

      - name: Install Android Command Line Tools
        id: command-line-tools-cache
        uses: ./.github/actions/download-verify-extract-cache-archive
        with:
          url: "https://dl.google.com/android/repository/commandlinetools-linux-${{ env.ANDROID_SDK_COMMAND_LINE_TOOLS_VERSION }}_latest.zip"
          checksum: ${{ env.CHECKSUM_ANDROID_SDK_COMMAND_LINE_TOOLS }}
          archive-type: zip
          extract-path: ${{ env.BIN_ANDROID_SDK_PATH }}
          cache-key-prefix: android-sdk-command-line-tools-${{ env.ANDROID_SDK_COMMAND_LINE_TOOLS_VERSION }}

      - name: Rename Android Command Line Tools Directory
        if: steps.command-line-tools-cache.outputs.cache-hit != 'true'
        run: |
          mv ${{ env.BIN_ANDROID_SDK_PATH }}/cmdline-tools ${{ env.BIN_ANDROID_SDK_PATH }}/${{ env.ANDROID_SDK_COMMAND_LINE_TOOLS_VERSION }}
          mkdir ${{ env.BIN_ANDROID_SDK_PATH }}/cmdline-tools
          mv ${{ env.BIN_ANDROID_SDK_PATH }}/${{ env.ANDROID_SDK_COMMAND_LINE_TOOLS_VERSION }} ${{ env.BIN_ANDROID_SDK_CMDLINE_TOOLS_PATH }}

      - name: Configure Java Home
        run: |
          echo "JAVA_HOME=${{ env.BIN_JDK_PATH }}" >> $GITHUB_ENV

      - name: Restore Installed Adoptium Temurin JDK
        uses: ./.github/actions/restore-cached-archive
        with:
          checksum: ${{ env.CHECKSUM_JDK }}
          extract-path: ${{ env.BIN_JDK_PATH }}
          cache-key-prefix: adoptium-temurin-${{ env.JDK_VERSION_TAG }}

      - name: Install Android SDK Toolchain
        run: |
          yes | ${{ env.BIN_ANDROID_SDK_CMDLINE_TOOLS_PATH }}/bin/sdkmanager --sdk_root=${{ env.BIN_ANDROID_SDK_PATH }} \
          "build-tools;${{ env.ANDROID_SDK_BUILD_TOOLS_VERSION }}" \
          "cmake;${{ env.ANDROID_SDK_CMAKE_VERSION }}" \
          "ndk;${{ env.ANDROID_SDK_NDK_VERSION }}" \
          "platforms;${{ env.ANDROID_SDK_PLATFORMS_VERSION }}" \
          "platform-tools"

  export-artifacts:
    needs: [check, install-android-sdk, install-godot, install-godot-templates, install-jdk]
    runs-on: ubuntu-slim

    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: "Android [DEBUG]"
            is-debug: true
            requires-jdk: true
            output-extension: ".apk"
          - preset: "Linux [DEBUG]"
            is-debug: true
            requires-jdk: false
            output-extension: ""
          - preset: "macOS [DEBUG]"
            is-debug: true
            requires-jdk: false
            output-extension: ".app"
          - preset: "Windows Desktop [DEBUG]"
            is-debug: true
            requires-jdk: false
            output-extension: ".exe"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Configure Godot Templates Environment
        run: |
          echo "ASSETS_GODOT_TEMPLATES_PATH=${HOME}/.local/share/godot/export_templates" >> $GITHUB_ENV

      - name: Restore Installed Godot
        uses: ./.github/actions/restore-cached-archive
        with:
          checksum: ${{ env.CHECKSUM_GODOT }}
          extract-path: ${{ env.BIN_GODOT_PATH }}
          cache-key-prefix: godot-${{ env.GODOT_VERSION }}

      - name: Restore Installed Godot Templates
        uses: ./.github/actions/restore-cached-archive
        with:
          checksum: ${{ env.CHECKSUM_GODOT_TEMPLATES }}
          extract-path: ${{ env.ASSETS_GODOT_TEMPLATES_PATH }}
          cache-key-prefix: godot-${{ env.GODOT_VERSION }}-templates

      - name: Restore Installed Adoptium Temurin JDK
        uses: ./.github/actions/restore-cached-archive
        if: matrix.requires-jdk
        with:
          checksum: ${{ env.CHECKSUM_JDK }}
          extract-path: ${{ env.BIN_JDK_PATH }}
          cache-key-prefix: adoptium-temurin-${{ env.JDK_VERSION_TAG }}

      - name: Add Godot to PATH
        run: |
          echo "${{ env.BIN_GODOT_PATH }}" >> $GITHUB_PATH

      - name: Configure Artifact Environment
        run: |
          ARTIFACT_NAME="${{ env.EXPORT_NAME }}.${{ env.GITHUB_RELEASE_VERSION }}.${{ env.REPOSITORY_HEAD_SHA }}.${{ env.PRESET_SLUG }}"

          echo "Formatted Artifact Name: $ARTIFACT_NAME"
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV

      - name: Configure Preset Environment
        run: |
          PRESET_SLUG=$(echo "${{ matrix.preset }}" \
            | tr '[:upper:]' '[:lower:]' \
            | sed \
            -e 's/[^a-z0-9]/-/g' \
            -e 's/-\+/-/g' \
            -e 's/^-\|-$//g')

          echo "Formatted Preset Slug: $PRESET_SLUG"
          echo "PRESET_SLUG=$PRESET_SLUG" >> $GITHUB_ENV

      - name: Configure Repository Information Environment
        run: |
          GITHUB_RELEASE_VERSION="${{ github.ref_name }}"
          REPOSITORY_HEAD_SHA="$(git rev-parse --short HEAD)"

          echo "Retrieved GitHub Release Version: $GITHUB_RELEASE_VERSION"
          echo "Retrieved Repository Head SHA256 Checksum: $REPOSITORY_HEAD_SHA"

          echo "GITHUB_RELEASE_VERSION=$GITHUB_RELEASE_VERSION" >> $GITHUB_ENV
          echo "REPOSITORY_HEAD_SHA=$REPOSITORY_HEAD_SHA" >> $GITHUB_ENV

      - name: Configure Java Home
        if: matrix.requires-jdk
        run: |
          echo "JAVA_HOME=${{ env.BIN_JDK_PATH }}" >> $GITHUB_ENV

      - name: Godot Version
        run: |
          ${{ env.BIN_GODOT_PATH }}/godot --version

      - name: Godot Templates Version
        run: |
          cat ${{ env.ASSETS_GODOT_TEMPLATES_PATH }}/${{ env.GODOT_VERSION }}.stable/version.txt

      - name: Adoptium Temurin JDK Version
        if: matrix.requires-jdk
        run: |
          cat ${{ env.BIN_JDK_PATH }}/release

      - name: Export ${{ matrix.preset }} Artifacts
        run: |
          mkdir -v -p artifacts/${{ env.PRESET_SLUG }}

          cd $PROJECT_PATH

          # NOTE: Editor-only addons need to be removed to prevent shipping with
          # artifacts and any errors they might cause.
          rm -rf ./addons/GDQuest_GDScript_formatter

          ARTIFACT_FILE_NAME="${{ env.ARTIFACT_NAME }}${{ matrix.output-extension }}"

          godot \
            --headless \
            --verbose \
            ${{ matrix.is-debug == true && '--export-debug' || '--export-release' }} "${{ matrix.preset }}" \
            "${GITHUB_WORKSPACE}/artifacts/${{ env.PRESET_SLUG }}/${ARTIFACT_FILE_NAME}"

      - name: Zip ${{ matrix.preset }} Artifacts
        run: |
          cd artifacts/${{ env.PRESET_SLUG }}
          zip -r "${GITHUB_WORKSPACE}/${{ env.ARTIFACT_NAME }}.zip" .

      - name: Upload ${{ matrix.preset }} Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}.zip

      - name: Release ${{ matrix.preset }} Artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ARTIFACT_NAME }}.zip
